### ISSUE TITLE
Sign In Page and Forget Password Page

### ISSUE THREAD

**Issue by justin-loi** [uh-manoa-meteorites/nonprofit-project-template#10]
Mock up of the sign-in page
doesn't have to be functional just look similar to the web press site
However, it may be good to think about how to implement the "Forget Password" and "Remember Me"

save as a branch named issue 10

**Comment by tracytnb** [comment]
Helpful links: 
https://docs.meteor.com/api/passwords.html#Accounts-forgotPassword
