### ISSUE TITLE
Review: Browse Opportunities by Category and Volunteer Signup Page

### ISSUE THREAD

**Issue by Irene-ma** [uh-manoa-meteorites/nonprofit-project-template#29]
## Overview

The focus for this code review will be centered around the landing and volunteer sign up page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

main

## Files to review

[LandingOpportunitiesByCategorySection.jsx](https://github.com/uh-manoa-meteorites/nonprofit-project-template/blob/main/app/imports/ui/components/LandingOpportunitiesByCategorySection.jsx)
[VolunteerSignup.jsx](https://github.com/uh-manoa-meteorites/nonprofit-project-template/blob/main/app/imports/ui/pages/VolunteerSignup.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)
* [UI](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-ui-checklist)

## Due date

02/01/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by cammoore** [comment]
## LandingOpportunitiesByCategorySection.jsx

AR-03: Is this file in the right directory? Do we want to separate the
components? (e.g. imports/ui/components/landing). Then we can shorten
the name of the Component.

JS-07: L4: Don't use /** comments and the comment is wrong.

L14,15: Why are we using className? Can't we use a semantic-ui-react
component? 
L16, 19: Why are we using className? Can't we use the properties of
Image? 

DE-07: L14-21: This should be a component we import and instantiate.

## VolunteerSignup.jsx

L14: Comment is misleading.

JS-04: L41, 48, 97, 108, 119, etc. Prefer arrow functions. 

L233: Why do volunteers have an owner?

L270-721: Should we be using Uniforms and a schema?

**Comment by nicholasbcarr** [comment]
JS-08: in browse by category, update javaDoc comment to reflect

Design-01: make catagory card component for the browse by catagory "category card" and a category collection containing name and images to populate as categories are updated or do we just have an other category for those that do not match a preset one

Design-01: do we have a make category page for the admin to add a category as new things arise

Design-01: we probably want a organization collection that can be used to store badges/images/logo/events/etc and to populate organization related components

UI-03: component needs to be a link to a page that renders events by the category that was selected

**Comment by glee25** [comment]
LandingOpportunitiesByCategorySection.jsx:
Design-05: Unnecessary comment on line 4

VolunteerSignup.jsx:
ESLINT-01: Typo on Line 22 setDateOfBrith should be setDateOfBirth
Typo on Line 25 setfirstName should be setFirstName
Typo on Line 26 setlastName should be setLastName

**Comment by Irene-ma** [comment]
Architecture
Arch-01: both files need to follow camel case naming convention
 
Design
Design-03: VolunteerSignup.jsx has commented out code that isnt being used
 
JS
JS-07: get rid of the commented out console.logs in VolunteerSignup.jsx
 
UI
UI-07: some console logs in VolunteerSignup.jsx

**Comment by justin-loi** [comment]
Volunteer Sign Up:
Repetitive Code
Comment Irrelevant

Land Opportunities:
Repetitive Code
Possible to do Destructuring

**Comment by tracytnb** [comment]
VolunteerSignUp.jsx:
Design-01: Line 101, possible grammatical error. "setError('Please make sure the both passwords match');" Could use reference from webpage, it says "Your passwords do not match"

**Comment by TricPham** [comment]
VolunteerSignUp:
line 48 isValidData, switch from string input to calender selection?

**Comment by sulao1999** [comment]
VolunteerSignUp.jsx:
UI-02: mobile screen sizes, some text goes beyond the border.
