### ISSUE TITLE
Review Issue #2: Events Card, Browse Events by Category and Events Collection

### ISSUE THREAD

**Issue by nicholasbcarr** [uh-manoa-meteorites/nonprofit-project-template#46]
## Overview

Ensuring the event card and browse events by category meet everything needed and ensuring no other data is needed or wanted for the event creation or event card component. The events collection should be reviewed alongside the events card.
   
Please pay attention too:
* Javascript issues
* React components

## Review Branch

main

## Files to review

* [EventCard.jsx](https://github.com/uh-manoa-meteorites/nonprofit-project-template/blob/main/app/imports/ui/components/EventCard.jsx)
* [BrowseOpportunities.jsx](https://github.com/uh-manoa-meteorites/nonprofit-project-template/blob/main/app/imports/ui/pages/BrowseOpportunities.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/campus-cravings/blob/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/blob/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/blob/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/blob/master/checklists/react-checklist.md)
* [UI](http://courses.ics.hawaii.edu/ics414s22/morea/review/checklists/reading-ui-checklist)

## Due date

Tuesday, Feb. 8 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by nicholasbcarr** [comment]
EventCard.jsx

UI-03: we may want to render on the card a logo indicating if the event is outside/inside

Note: This may be where we want our add to calendar or share on twitter action? Like directly on the card?

BrowseEvents.jsx

UI-01: render three random cards but use a dropdown selector for category choice? Radio Field to indicate special skills or do we bring those from the user profile and apply automatically?

UI-03: what categories would we like to browse by? Indoor/Outdoor and Labor Intensive categories might seem logical for event creation?

UI-03: in the event creation, we will want both the category of event and what special skills it caters to because there is no link between those at the moment. Should we just automatically render cards that relate to special skills?

**Comment by Irene-ma** [comment]
### EventCard.jsx
Arch-01: Camel case lettering for the name
UI-07: page generated a console log error

### BrowseOpportunities.jsx 
Arch-01: Camel case lettering for the name
Design-05: Comments seem to be confusing, not clear. Code in the comments
UI-01: Have a way to search for opportunities based on category or filters
UI-03: Have the entire card move upon hover or something to indicate that the card can be clicked on, or make the links easily visible

**Comment by glee25** [comment]
**EventCard.jsx**:
JS-08: Unnecessary JSDoc comment.

**BrowseOppurtunity.jsx**:
Design-04: Eliminate large comment blocks
Design-05: Unnecessary comments. Commented out code on lines 26-29.

**Comment by justin-loi** [comment]
Event Card.jsx

JS-08: Should use regular comment (not JSDoc) and the comment is wrong.
UI-03: The link in Card Header is not obvious
Arch-01: Camel Case

BrowseOpportunities.jsx

L26-32 excluding 30: Code in comments
L10: Container ID is wrong
Arch-01: Camel Case
*Need to decide how each collection is structured to make this page better

**Comment by TricPham** [comment]
**BrowseOpportunities.jsx:**
Arch-01: titles should follow the same naming convention
UI-03: clickable link needs to be obvious.
UI-03: organization name are interactive but hard to tell and doesn't do anything.

**Comment by tracytnb** [comment]
EventCard.jsx:
L8: Typo in line 8, remove the equals sign
L11: "/eprofile" could possibly change it to something more descriptive

BrowseOpportunities.jsx:
Design-08: Double check with ESLint. Certain spacing between lines are not there.

**Comment by sulao1999** [comment]
UI-02: Event card touch footer

**Comment by cammoore** [comment]
## EventCard.jsx

L6: Why are you talking about Stuff?
L8: What is the =?
L11: Is /eprofile the right route?
L21: You end up with a trailing ','
L41: event._id isn't used.

## BrowseOpportunities.jsx

L13: index is not a good key. You can use event._id.
L34: The individual events don't have an _id field.
